import { RoleBasedLinks } from "@/types";
import {
  Bell,
  BookCheck,
  BriefcaseBusiness,
  Calendar,
  DollarSign,
  File,
  FilePlus,
  FileQuestion,
  FileStack,
  Home,
  Info,
  LayoutDashboard,
  LibraryBig,
  MessageCircle,
  MessageCircleWarning,
  Search,
  Settings,
  ShoppingCart,
  Text,
  Users,
  Workflow,
} from "lucide-react";

export const roleBasedSideBarLinks: RoleBasedLinks = {
  admin: [
    {
      id: 0,
      type: "profile",
      pattern: "/me/[id]",
    },
    {
      id: 1,
      label: "Dashboard",
      icon: Home,
      path: "/admin",
    },
    {
      id: 2,
      label: "Manage Users",
      icon: Workflow,
      type: "collapse",
      links: [
        {
          id: 21,
          label: "Manage All Users",
          icon: BriefcaseBusiness,
          path: "/admin/users",
          type: "supLink",
        },
        {
          id: 22,
          label: "Manage Employers",
          icon: BriefcaseBusiness,
          path: "/admin/users/employers",
          type: "supLink",
        },
        {
          id: 23,
          label: "Manage Job Seekers",
          icon: BriefcaseBusiness,
          path: "/admin/users/seekers",
          type: "supLink",
        },
      ],
    },
    {
      id: 6,
      label: "Content",
      icon: BriefcaseBusiness,
      type: "collapse",
      links: [
        {
          id: 61,
          label: "Home Page",
          icon: BriefcaseBusiness,
          path: "/admin/users",
          type: "supLink",
        },
        {
          id: 62,
          label: "Search Page",
          icon: BriefcaseBusiness,
          path: "/admin/users/employers",
          type: "supLink",
        },
        {
          id: 63,
          label: "Company Page",
          icon: BriefcaseBusiness,
          path: "/admin/users/seekers",
          type: "supLink",
        },
        {
          id: 64,
          label: "Seeker Page",
          icon: BriefcaseBusiness,
          path: "/admin/users/seekers",
          type: "supLink",
        },
      ],
    },
    {
      id: 7,
      label: "Manage Jobs",
      icon: BriefcaseBusiness,
      path: "/admin/jobs",
    },
    {
      id: 8,
      label: "Manage Applications",
      icon: BriefcaseBusiness,
      path: "/admin/Applications",
    },
    {
      id: 11,
      label: "Billing & Subscription",
      icon: BriefcaseBusiness,
      path: "/employer/subscription-plans",
    },
    {
      id: 12,
      label: "Report",
      icon: BriefcaseBusiness,
    },
    {
      id: 13,
      label: "Chat",
      icon: BriefcaseBusiness,
      path: "/chat",
      notifications: 3,
    },
    {
      id: 40,
      icon: BriefcaseBusiness,
      label: "Notifications",
      path: "/notifications",
      notifications: 4,
    },
    {
      id: 15,
      type: "text",
      section: "Settings",
    },
    {
      id: 16,
      label: "Settings",
      icon: BriefcaseBusiness,
      path: "/admin/setting",
    },
    {
      id: 17,
      label: "Help Center",
      icon: BriefcaseBusiness,
    },
  ],
  default: [
    {
      id: 1,
      label: "Home",
      icon: Home,
      path: "/",
    },
    {
      id: 2,
      label: "Courses",
      icon: Search,
      path: "/courses",
      pattern: "/courses/*",
    },
    {
      id: 3,
      label: "Blogs",
      icon: Text,
      path: "/blogs",
      pattern: "/blogs/*",
    },
  ],
  instructor: [
    {
      id: 0,
      type: "profile",
      pattern: "/in/[id]",
    },
    {
      id: 1,
      label: "Dashboard",
      icon: LayoutDashboard,
      path: "/instructor/dashboard",
    },
    {
      id: 2,
      label: "Courses",
      icon: BookCheck,
      type: "collapse",
      links: [
        {
          id: 1,
          label: "All Courses",
          icon: LibraryBig,
          path: "/instructor/courses",
          pattern: "/instructor/courses/*",
          type: "supLink",
        },
        {
          id: 2,
          label: "Add New Course",
          icon: FilePlus,
          path: "/instructor/add-course",
          type: "supLink",
        },
        {
          id: 3,
          label: "Resources",
          icon: File,
          path: "#",
          type: "supLink",
        },
      ],
    },
    {
      id: 3,
      label: "Quizzes",
      icon: FileQuestion,
      type: "collapse",
      links: [
        {
          id: 1,
          label: "All Quizzes",
          icon: FileStack,
          path: "/instructor/quizzes",
          type: "supLink",
        },
        {
          id: 2,
          label: "Add New Quiz",
          icon: FilePlus,
          path: "/instructor/add-quiz",
          type: "supLink",
        },
      ],
    },
    {
      id: 4,
      label: "Students",
      icon: Users,
      path: "/instructor/students",
    },
    {
      id: 5,
      label: "Financial",
      icon: DollarSign,
      path: "/instructor/financial",
    },
    {
      id: 6,
      label: "Schedule",
      icon: Calendar,
      path: "/instructor/schedule",
    },
    {
      id: 7,
      label: "Report",
      path: "#",
      icon: MessageCircleWarning,
    },
    {
      id: 8,
      label: "Chat",
      icon: MessageCircle,
      path: "/chat",
      notifications: 3,
    },
    {
      id: 9,
      icon: Bell,
      label: "Notifications",
      path: "#",
      notifications: 4,
    },
    {
      id: 10,
      type: "text",
      section: "Settings",
    },
    {
      id: 11,
      label: "Settings",
      icon: Settings,
      path: "/instructor/settings",
    },
    {
      id: 12,
      label: "Help Center",
      path: "#",
      icon: Info,
    },
  ],
  student: [
    {
      id: 1,
      type: "profile",
      pattern: "/st/[id]",
    },
    {
      id: 2,
      label: "Dashboard",
      icon: LayoutDashboard,
      path: "#",
    },
    {
      id: 3,
      icon: LibraryBig,
      label: "My Courses",
      path: "#",
    },
    {
      id: 4,
      label: "Explore Courses",
      icon: Search,
      path: "/courses",
      pattern: "/courses/*",
    },

    {
      id: 5,
      icon: Bell,
      label: "Notifications",
      path: "#",
      notifications: 4,
    },
    {
      id: 6,
      icon: ShoppingCart,
      label: "Cart",
      path: "/cart",
      notifications: 4,
    },
    {
      id: 7,
      icon: MessageCircle,
      label: "Messages",
      path: "/chat",
      notifications: 4,
    },

    {
      id: 8,
      section: "Settings",
      type: "text",
    },
    {
      id: 9,
      icon: Settings,
      label: "Settings",
      path: "#",
    },
    {
      id: 10,
      icon: Info,
      label: "Help Center",
      path: "#",
    },
  ],
};
