import { RoleBasedLinks } from "@/types";
import { BriefcaseBusiness, Home, Search, Text, Workflow } from "lucide-react";

export const roleBasedSideBarLinks: RoleBasedLinks = {
  admin: [
    {
      id: 0,
      type: "profile",
      pattern: "/me/[id]",
    },
    {
      id: 1,
      label: "Dashboard",
      icon: Home,
      path: "/admin",
    },
    {
      id: 2,
      label: "Manage Users",
      icon: Workflow,
      type: "collapse",
      links: [
        {
          id: 21,
          label: "Manage All Users",
          icon: BriefcaseBusiness,
          path: "/admin/users",
          type: "supLink",
        },
        {
          id: 22,
          label: "Manage Employers",
          icon: BriefcaseBusiness,
          path: "/admin/users/employers",
          type: "supLink",
        },
        {
          id: 23,
          label: "Manage Job Seekers",
          icon: BriefcaseBusiness,
          path: "/admin/users/seekers",
          type: "supLink",
        },
      ],
    },
    {
      id: 6,
      label: "Content",
      icon: BriefcaseBusiness,
      type: "collapse",
      links: [
        {
          id: 61,
          label: "Home Page",
          icon: BriefcaseBusiness,
          path: "/admin/users",
          type: "supLink",
        },
        {
          id: 62,
          label: "Search Page",
          icon: BriefcaseBusiness,
          path: "/admin/users/employers",
          type: "supLink",
        },
        {
          id: 63,
          label: "Company Page",
          icon: BriefcaseBusiness,
          path: "/admin/users/seekers",
          type: "supLink",
        },
        {
          id: 64,
          label: "Seeker Page",
          icon: BriefcaseBusiness,
          path: "/admin/users/seekers",
          type: "supLink",
        },
      ],
    },
    {
      id: 7,
      label: "Manage Jobs",
      icon: BriefcaseBusiness,
      path: "/admin/jobs",
    },
    {
      id: 8,
      label: "Manage Applications",
      icon: BriefcaseBusiness,
      path: "/admin/Applications",
    },
    {
      id: 11,
      label: "Billing & Subscription",
      icon: BriefcaseBusiness,
      path: "/employer/subscription-plans",
    },
    {
      id: 12,
      label: "Report",
      icon: BriefcaseBusiness,
    },
    {
      id: 13,
      label: "Chat",
      icon: BriefcaseBusiness,
      path: "/chat",
      notifications: 3,
    },
    {
      id: 40,
      icon: BriefcaseBusiness,
      label: "Notifications",
      path: "/notifications",
      notifications: 4,
    },
    {
      id: 15,
      type: "text",
      section: "Settings",
    },
    {
      id: 16,
      label: "Settings",
      icon: BriefcaseBusiness,
      path: "/admin/setting",
    },
    {
      id: 17,
      label: "Help Center",
      icon: BriefcaseBusiness,
    },
  ],
  default: [
    {
      id: 1,
      label: "Home",
      icon: Home,
      path: "/",
    },
    {
      id: 2,
      label: "Courses",
      icon: Search,
      path: "/courses",
      pattern: "/courses/*",
    },
    {
      id: 3,
      label: "Blogs",
      icon: Text,
      path: "/blogs",
      pattern: "/blogs/*",
    },
  ],
  instructor: [
    {
      id: 0,
      type: "profile",
      pattern: "/co/[id]",
    },
    {
      id: 1,
      label: "Dashboard",
      icon: Home,
      path: "/employer/dashboard",
    },
    {
      id: 2,
      label: "Company Info",
      icon: Home,
      path: "/employer/company-info",
    },
    {
      id: 3,
      label: "Jobs",
      icon: Home,
      type: "collapse",
      links: [
        {
          id: 4,
          label: "Manage Jobs",
          icon: Home,
          path: "/employer/job/manage-jobs",
          pattern: "/employer/job/manage-jobs/*",
          type: "supLink",
        },
        {
          id: 5,
          label: "Post New Job",
          icon: Home,
          path: "/employer/job/posted",
          pattern: "/employer/job/posted/*",
          type: "supLink",
        },
      ],
    },
    {
      id: 7,
      label: "Search",
      icon: Search,
      type: "collapse",
      links: [
        {
          id: 8,
          label: "Search",
          icon: Search,
          path: "/employer/search",
          type: "supLink",
        },
        {
          id: 10,
          label: "My Folders",
          icon: Home,
          path: "/employer/search/saved-search",
          pattern: "/employer/search/saved-search/*",
          type: "supLink",
        },
      ],
    },
    {
      id: 11,
      label: "Billing & Subscription",
      icon: Home,
      path: "/employer/subscription-plans",
    },
    {
      id: 12,
      label: "Report",
      icon: Home,
    },
    {
      id: 13,
      label: "Chat",
      icon: Home,
      path: "/chat",
      notifications: 3,
    },
    {
      id: 40,
      icon: Home,
      label: "Notifications",
      path: "/notifications",
      notifications: 4,
    },
    {
      id: 15,
      type: "text",
      section: "Settings",
    },
    {
      id: 16,
      label: "Settings",
      icon: Home,
      path: "/employer/setting",
    },
    {
      id: 17,
      label: "Help Center",
      icon: Home,
    },
  ],
  student: [
    {
      id: 0,
      type: "profile",
      pattern: "/me/[id]",
    },
    // {
    //   id: 18,
    //   icon: HomeOutlined,
    //   label: "Home",
    //   path: "/",
    // },
    {
      id: 20,
      icon: Home,
      label: "Messages",
      path: "/chat",
      notifications: 3,
    },
    {
      id: 21,
      icon: Home,
      label: "My Applications",
      path: "/job-seeker/my-applications",
    },
    {
      id: 22,
      icon: Home,
      label: "Find Jobs",
      path: "/search",
    },
    {
      id: 23,
      icon: Home,
      label: "Browse Companies",
      path: "/job-seeker/browse-companies",
    },
    {
      id: 24,
      icon: Home,
      label: "Notifications",
      path: "/notifications",
      notifications: 4,
    },

    {
      id: 26,
      section: "Settings",
      type: "text",
    },
    {
      id: 27,
      icon: Home,
      label: "Settings",
      path: "/job-seeker/setting",
      pattern: "/job-seeker/setting/*",
    },
    {
      id: 28,
      icon: Home,
      label: "Help Center",
      path: "#",
    },
  ],
};
