import { DM_Serif_Display, Poppins } from "next/font/google";
import "./globals.css";
import { NextAuthProvider } from "@/NextAuthProvider";
import DynamicHeader from "@/components/Layout/Header/Header";
import DynamicLayout from "@/components/Layout/layout";
import Footer from "@/components/Layout/Footer/footer";

const dmSerifDisplay = DM_Serif_Display({
  subsets: ["latin"],
  variable: "--font-dmSerif",
  weight: "400",
});

const poppins = Poppins({
  subsets: ["latin"],
  variable: "--font-poppins",
  weight: ["400", "500", "600", "700"],
});

export const metadata = {
  title: "Medicova",
  description: "Generated by Next.js",
};
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <title>Medicova</title>
      <body
        className={`${dmSerifDisplay.variable}  ${poppins.variable} font-poppins`}>
        <NextAuthProvider>
          <DynamicHeader />
          <DynamicLayout>{children}</DynamicLayout>
          <Footer />
        </NextAuthProvider>
      </body>
    </html>
  );
}
