import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { NextAuthProvider } from "@/NextAuthProvider";
import DynamicHeader from "@/components/Layout/Header/Header";
import DynamicLayout from "@/components/Layout/layout";
import Footer from "@/components/Layout/Footer/footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <title>Medicova</title>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <NextAuthProvider>
          <DynamicHeader />
          <DynamicLayout>{children}</DynamicLayout>
          <Footer />
        </NextAuthProvider>
      </body>
    </html>
  );
}
